# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: $(imageName)

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.203'
- cmd: dotnet tool install -g GitVersion.Tool --version 5.0.0-beta2-64
- cmd: dotnet gitversion > version.json
- script: dotnet --version